#![feature(proc_macro)]
#![recursion_limit = "128"]

extern crate proc_macro;

#[macro_use]
extern crate quote;

use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn module(_args: TokenStream, _input: TokenStream) -> TokenStream {
    // Code is generated by build.rs, so eat all the tokens...
    let expanded = quote! {
        include!(concat!(env!("OUT_DIR"), "/verilator.rs"));
    };

    expanded.into()
}
